[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bact_pheno"
version = "0.1.0"
description = "Bact pheno package"
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Torbjorn Regueira", email = "s203555@dtu.dk" }]
dependencies = ["torch", 
                "numpy", 
                "scikit-learn", 
                "matplotlib", 
                "seaborn",
                "pandas",
                "argparse",
                "tqdm",
                "wandb",
                "esm",
                "biopython",
                "joblib"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]